var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(workspace)/inteligencia/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__01y76ru._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1afq_id.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1ypm6fc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__13-b0sw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06-389a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_0zdx4nm._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(workspace)_inteligencia_page_actions_1lu1kha.js")
R.m(21846)
module.exports=R.m(21846).exports
