import type { ContextHelpAreaDefinition, ContextHelpTopic } from "@/lib/context-help";

const GENERAL_TOPICS: readonly ContextHelpTopic[] = [
  {
    id: "sobre-o-minerador",
    title: "Para que serve o Minerador",
    summary: "Descobre, organiza e qualifica keywords da marca ativa antes da formação editorial.",
    description: "O Minerador reúne Descobrir, Processar, métricas, leitura lógica, KGR, revisão e decisão. Ele prepara o KeywordDNA para o Arquiteto; não forma artigos nem publica conteúdo.",
    sections: [
      { heading: "O que faz", body: "Ajuda a encontrar candidatas, conferir evidências e transformar cada keyword em uma leitura rastreável." },
      { heading: "O que não faz", body: "A leitura inicial não é a verdade final, a IA não aprova sozinha e o Minerador não substitui a decisão editorial do Arquiteto." },
    ],
    howToUse: [
      "Confira a marca ativa antes de operar.",
      "Use Descobrir para explorar e Processar para conferir e decidir.",
      "Leia o Perfil da Keyword quando precisar de contexto completo.",
    ],
    keywords: ["processar keywords", "descoberta", "listas", "keyworddna", "arquiteto", "marca ativa"],
  },
  {
    id: "ordem-recomendada",
    title: "Ordem recomendada para processar uma keyword",
    summary: "Siga a sequência lógica → Volume → Resultados → KGR → IA → Revisar → Status.",
    description: "Cada etapa acrescenta evidências ao DNA. A lógica propõe uma leitura, os provedores medem fatos, a IA revisa e a pessoa consolida a decisão.",
    howToUse: [
      "Execute Lógica para criar a leitura inicial.",
      "Atualize Volume e meça Resultados quando precisar dos fatos quantitativos.",
      "Execute IA e Revisar somente depois de reunir o contexto necessário.",
    ],
    keywords: ["fluxo", "etapas", "processar", "volume", "resultados", "kgr", "ia", "revisão", "status"],
  },
  {
    id: "processo-revisao-decisao",
    title: "Entenda processo, revisão e decisão",
    summary: "Processar prepara o DNA; revisar resolve pendências; decidir define o estado final.",
    description: "Uma etapa concluída não significa aprovação. A IA sugere, a revisão humana resolve divergências e o Status final registra a decisão do usuário.",
    sections: [
      { heading: "Depois da revisão", body: "Confira se as pendências foram resolvidas e se o DNA está confirmado antes de usar a keyword em outra etapa." },
      { heading: "Importante", body: "Vínculo com publicação e Status editorial são informações diferentes: uma keyword pode estar aprovada sem estar publicada." },
    ],
    keywords: ["revisão humana", "decisão", "aprovação", "dna confirmado", "publicação", "status"],
  },
];

const DISCOVERY_TOPICS: readonly ContextHelpTopic[] = [
  {
    id: "descobrir-visao-geral",
    title: "Encontrar novas oportunidades de busca",
    summary: "Use Descobrir para gerar candidatas reais a partir de uma palavra, serviço, produto ou nicho.",
    description: "A Descoberta consulta ideias de keyword e organiza os candidatos para uma triagem inicial. Os dados que aparecem ali são informativos e podem ser revalidados depois no Processador.",
    howToUse: [
      "Escolha o tipo de descoberta e informe a semente.",
      "Ajuste targeting e filtros somente se isso ajudar a triagem.",
      "Selecione as candidatas que deseja enviar ao Processador.",
    ],
    keywords: ["descobrir keywords", "oportunidades", "candidatas", "pesquisa", "seed", "ideias"],
  },
  {
    id: "descobrir-palavra-chave",
    title: "Expandir uma palavra-chave conhecida",
    summary: "O modo Palavra-chave parte de um termo conhecido e encontra ideias relacionadas.",
    description: "Digite uma palavra-chave principal, serviço, produto ou nicho para receber termos relacionados. As sugestões vêm da consulta de descoberta; o Minerador não fabrica keywords.",
    howToUse: [
      "Selecione Palavra-chave em Tipo de descoberta.",
      "Digite pelo menos o termo principal e confira a relação escolhida.",
      "Pesquise e faça a triagem na tabela retornada.",
    ],
    keywords: ["palavra-chave", "expandir", "relacionadas", "termo conhecido", "seed"],
  },
  {
    id: "descobrir-como-clientes-encontram",
    title: "Descobrir buscas pela perspectiva do cliente",
    summary: "O modo Como clientes me encontram prioriza formas de procura ligadas ao serviço ou produto informado.",
    description: "Esse modo usa a mesma geração de ideias, mas organiza a leitura pela perspectiva de potenciais clientes. Cliente provável, ambígua e outra perspectiva são classificações leves da Descoberta, não KeywordDNA consolidado.",
    howToUse: [
      "Selecione Como clientes me encontram.",
      "Informe o produto, serviço ou nicho.",
      "Use a coluna Perspectiva para priorizar a triagem sem apagar os demais candidatos.",
    ],
    keywords: ["como clientes me encontram", "cliente provável", "perspectiva", "comportamento de cliente", "contratar"],
  },
  {
    id: "descobrir-modo-enfoque",
    title: "Controlar o tipo de oportunidade procurada",
    summary: "Tipo de descoberta e Enfoque mudam a forma de organizar a pesquisa, não a origem dos dados.",
    description: "Use o Tipo de descoberta para alternar entre expandir uma keyword e observar como clientes procuram um serviço. No modo de cliente, Enfoque pode priorizar todos os comportamentos ou encontrar/contratar.",
    sections: [
      { heading: "O que acontece", body: "A consulta continua usando ideias reais e o enfoque dá prioridade visual à triagem." },
      { heading: "O que não acontece", body: "O controle não transforma uma candidata em cliente provável por si só e não cria uma intenção canônica." },
    ],
    keywords: ["tipo de descoberta", "enfoque", "todos os comportamentos", "encontrar", "contratar"],
  },
  {
    id: "descobrir-intencao-preliminar",
    title: "Usar intenção como filtro inicial",
    summary: "A intenção preliminar ajuda a organizar a Descoberta, mas ainda não é a intenção canônica.",
    description: "Escolha uma intenção preliminar quando quiser restringir a exploração. O Processador executa a leitura lógica atual e a revisão humana continua sendo a autoridade para a intenção consolidada.",
    keywords: ["intenção preliminar", "intenção", "informativa", "comercial", "transacional", "canônica"],
  },
  {
    id: "descobrir-funil-preliminar",
    title: "Filtrar a Descoberta pela etapa da jornada",
    summary: "O funil preliminar ajuda a separar candidatas por etapa provável da jornada.",
    description: "Use a etapa do funil como contexto inicial da pesquisa. Ela acompanha a candidata para orientar a triagem, mas o Funil canônico é derivado e revisado no Processador.",
    keywords: ["funil preliminar", "etapa do funil", "jornada", "topo", "meio", "fundo"],
  },
  {
    id: "descobrir-targeting",
    title: "Definir onde e em que contexto pesquisar",
    summary: "Idioma, país e Estados/UF definem o contexto da pesquisa; Moeda apenas informa a apresentação monetária.",
    description: "Confira o idioma, o país e as UFs antes de pesquisar. No contexto brasileiro, a interface apresenta R$ · BRL para ajudar a interpretar Volume e CPC; isso não altera a moeda bruta retornada pelo Google Ads.",
    sections: [
      { heading: "Quando ajustar", body: "Ajuste o targeting quando a demanda que você quer observar estiver ligada a outro idioma ou território." },
      { heading: "Moeda", body: "Moeda é somente leitura e contexto da pesquisa. O valor real retornado em uma medição tem precedência nos dados medidos." },
    ],
    keywords: ["targeting", "idioma", "país", "brasil", "estados", "uf", "moeda", "r$", "brl"],
  },
  {
    id: "descobrir-filtros",
    title: "Reduzir a lista de candidatas",
    summary: "Use Volume, CPC, Resultado, KD e termos incluídos/excluídos para fazer a triagem.",
    description: "Os filtros apenas escondem da lista as candidatas que não correspondem aos critérios atuais. Resultado e KD dependem de medição SEO explícita; a Descoberta não chama DataForSEO ao alterar um filtro.",
    howToUse: [
      "Escolha os filtros prontos ou abra Intervalo personalizado.",
      "Informe mínimo e máximo quando precisar de uma faixa própria.",
      "Limpe os filtros para voltar a ver todos os candidatos.",
    ],
    keywords: ["filtros", "volume", "cpc", "resultado", "kd", "incluir", "excluir", "intervalo personalizado"],
  },
  {
    id: "descobrir-faixas-numericas",
    title: "Escolher uma faixa pronta ou personalizada",
    summary: "Resultado e KD usam faixas numéricas para triagem, sem classificar a keyword como boa ou ruim.",
    description: "As faixas prontas facilitam a navegação. Resultado é a quantidade medida na concorrência orgânica e KD é uma estimativa numérica de dificuldade; interprete ambos junto com Volume e KGR.",
    sections: [
      { heading: "Sem medição", body: "Uma candidata sem Resultado ou KD medido não deve ser tratada como zero. Use Sem medição quando quiser encontrar esse estado." },
      { heading: "Personalizado", body: "Selecione Intervalo personalizado para informar os limites mínimo e máximo." },
    ],
    keywords: ["faixas", "resultado", "kd", "0–20", "0-20", "sem medição", "com resultado", "personalizado"],
  },
  {
    id: "descobrir-organizar",
    title: "Ordenar a Descoberta",
    summary: "Organize a tabela para encontrar mais rapidamente as candidatas que deseja selecionar.",
    description: "Use Organizar para escolher a ordenação disponível e Limpar organização para retornar ao estado sem ordenação aplicada. Ordenar muda a visualização, não os dados da candidata.",
    keywords: ["organizar", "ordenar", "crescente", "decrescente", "limpar organização", "ordem"],
  },
  {
    id: "descobrir-tabela",
    title: "Entender os candidatos da Descoberta",
    summary: "A tabela mostra a keyword, a perspectiva e as métricas disponíveis para a triagem.",
    description: "Volume e CPC podem vir da consulta de demanda; Resultado e KD aparecem quando houver medição SEO. Intenção e Funil são preliminares e a origem indica como o candidato chegou à lista.",
    sections: [
      { heading: "Leitura correta", body: "Uma célula vazia ou um traço significa que o dado não está disponível naquela candidata, não que o valor seja zero." },
      { heading: "Próximo passo", body: "Selecione os candidatos úteis e envie-os ao Processador para a validação oficial." },
    ],
    keywords: ["tabela", "candidatos", "perspectiva", "origem", "google ads", "csv", "manual"],
  },
  {
    id: "descobrir-atualizar-metricas",
    title: "Consultar novamente a demanda disponível",
    summary: "Atualizar métricas consulta novamente no Google Ads Volume, CPC e outras métricas disponíveis.",
    description: "Essa ação é opcional na Descoberta e serve para melhorar a triagem. Ela não certifica a keyword no Processador nem substitui a revalidação oficial daquele fluxo.",
    howToUse: [
      "Selecione uma ou mais candidatas.",
      "Acione Atualizar métricas e aguarde o aviso de conclusão.",
      "Confira os valores atualizados na tabela antes de selecionar as candidatas.",
    ],
    keywords: ["atualizar métricas", "google ads", "volume", "cpc", "demanda", "descoberta"],
  },
  {
    id: "descobrir-medir-resultados",
    title: "Consultar a concorrência orgânica",
    summary: "Medir resultados consulta Resultado e KD disponíveis para as candidatas selecionadas.",
    description: "A ação é opcional e pode consumir a consulta SEO disponível. Resultado é a quantidade da medição orgânica usada pelo Minerador; internamente essa evidência pode ser identificada como allintitle.",
    sections: [
      { heading: "Quando usar", body: "Use depois de reduzir a lista por demanda, quando quiser comparar a concorrência de um grupo menor." },
      { heading: "Limite", body: "A presença do valor na Descoberta não marca Resultados como validado no Processador; a keyword será revalidada lá." },
    ],
    keywords: ["medir resultados", "resultado", "allintitle", "kd", "dataforseo", "concorrência orgânica"],
  },
  {
    id: "descobrir-enviar-processador",
    title: "Enviar candidatas ao Processador",
    summary: "Envie somente as candidatas selecionadas, com os dados disponíveis e sua proveniência preservada.",
    description: "O envio não exige Volume, Resultado ou KD medidos na Descoberta. Esses dados acompanham a origem como contexto; o Processador revalida as etapas antes da decisão final.",
    howToUse: [
      "Selecione as candidatas desejadas.",
      "Acione Enviar selecionadas ao Processador.",
      "Depois, execute as etapas oficiais que ainda estiverem pendentes.",
    ],
    keywords: ["enviar ao processador", "enviar selecionadas", "importar", "proveniência", "snapshot", "revalidar"],
  },
  {
    id: "descobrir-selecao",
    title: "Usar a seleção e a barra de ações",
    summary: "A seleção controla as ações do lote; ela não abre um resumo semântico global.",
    description: "Selecione uma ou várias candidatas para atualizar métricas, medir resultados ou enviar ao Processador. Os detalhes permanecem na linha e nos dados da keyword, sem misturar o contexto de uma seleção anterior.",
    keywords: ["seleção", "bulk", "lote", "barra de ações", "selecionadas"],
  },
  {
    id: "descobrir-colar-keywords",
    title: "Adicionar uma lista rapidamente",
    summary: "Cole várias keywords para preparar uma descoberta ou uma lista de candidatas sem digitar uma por uma.",
    description: "Use a entrada de colagem quando já tiver termos em linhas ou separados pelo formato aceito pela tela. Revise a lista antes de confirmar e preserve a marca ativa.",
    keywords: ["colar keywords", "colar", "lista", "várias keywords", "texto"],
  },
  {
    id: "descobrir-importar-csv",
    title: "Trazer keywords de um CSV",
    summary: "Importe uma planilha CSV para a Descoberta e confira a coluna Keyword antes de confirmar.",
    description: "A coluna Keyword é a referência obrigatória. Volume, Resultado e outros dados presentes podem ser aproveitados como contexto, mas não substituem a validação posterior do Processador.",
    sections: [
      { heading: "Antes de importar", body: "Confira o arquivo, a marca ativa e se os termos estão na coluna esperada." },
      { heading: "Depois de importar", body: "Revise duplicidades, origem e métricas antes de selecionar o que seguirá para o Processador." },
    ],
    keywords: ["csv", "importar csv", "planilha", "coluna keyword", "arquivo", "importação"],
  },
];

const PROCESSOR_TOPICS: readonly ContextHelpTopic[] = [
  {
    id: "processar-visao-geral",
    title: "Transformar uma keyword em KeywordDNA",
    summary: "Processar reúne leitura, evidências, revisão e decisão em torno de uma keyword.",
    description: "A planilha mostra um resumo operacional e o Perfil da Keyword guarda a leitura completa. Use a seleção para executar uma etapa em lote e expanda uma linha para examinar aquele DNA específico.",
    howToUse: [
      "Selecione a keyword na planilha.",
      "Execute somente a etapa que deseja validar.",
      "Abra o Perfil para comparar evidências e concluir a revisão.",
    ],
    keywords: ["processar keywords", "keyworddna", "processador", "perfil da keyword", "planilha"],
  },
  {
    id: "processar-fluxo",
    title: "Usar a sequência de processos",
    summary: "A barra de processos mostra as etapas validadas no Processador, não apenas dados importados.",
    description: "Lógica, Volume e Resultados recebem confirmação após sua execução no Processador. KGR é automático; IA e Revisão dependem das condições próprias de cada etapa.",
    sections: [
      { heading: "Importante", body: "Uma medição trazida da Descoberta permanece como histórico ou contexto até ser revalidada no Processador." },
      { heading: "Acompanhe", body: "Use a barra de progresso e os avisos para saber o que foi executado e abra a linha para ler o resultado persistido." },
    ],
    keywords: ["barra de processos", "etapas validadas", "lógica", "volume", "resultados", "kgr", "ia", "revisão"],
  },
  {
    id: "processar-tabela",
    title: "Usar a planilha para tomar decisões",
    summary: "A planilha resume vínculo, métricas, leitura canônica, organização e status.",
    description: "Keyword, Vínculo, Resultados, Volume, KGR, CPC, KD, Intenção, Nicho, Funil, Silo/Categoria e Status ajudam na triagem. As colunas de leitura são informativas; Silo/Categoria e Status são os campos operacionais editáveis da linha.",
    keywords: ["tabela", "planilha", "colunas", "vínculo", "resultados", "volume", "kgr", "cpc", "kd", "intenção", "nicho", "funil", "silo", "status"],
  },
  {
    id: "processar-selecao",
    title: "Selecionar keywords no Processador",
    summary: "A seleção define o lote das ações e não troca o contexto do Perfil da Keyword.",
    description: "Selecione uma ou várias linhas para usar a barra inferior. O resultado de uma execução aparece no aviso, na tabela e no KeywordDNA individual; não há um painel global de resultado semântico.",
    keywords: ["seleção", "lote", "bulk bar", "barra inferior", "painel global", "resultado"],
  },
  {
    id: "vinculo",
    title: "Vínculo com conteúdo publicado",
    summary: "Vínculo mostra a relação da keyword com uma página existente, sem substituir o Status editorial.",
    description: "Uma keyword pode estar livre, ter uma página candidata, ser verificada ou estar vinculada a uma publicação. Conferir site atualiza essa evidência; publicar é outro processo.",
    keywords: ["vínculo", "publicado", "página", "site", "url", "livre", "publicação"],
  },
  {
    id: "processar-resultados",
    title: "Resultado",
    summary: "Resultado é a quantidade real de concorrência orgânica medida para a expressão.",
    description: "A interface usa Resultado como linguagem humana. A proveniência preserva que a medição veio da consulta allintitle do DataForSEO, com seus dados técnicos e histórico.",
    sections: [
      { heading: "Como interpretar", body: "Leia Resultado junto com Volume e KGR; sozinho, ele não é uma nota de dificuldade SEO." },
      { heading: "Quando falta", body: "Ausência de medição é diferente de Resultado igual a zero." },
    ],
    keywords: ["resultados", "resultado", "allintitle", "dataforseo", "concorrência", "medição orgânica"],
  },
  {
    id: "processar-volume",
    title: "Volume",
    summary: "Volume é a demanda mensal medida pelo Google Ads no contexto configurado.",
    description: "Volume representa a procura disponível para a keyword no targeting da medição. O valor importado da Descoberta não valida a etapa; o Processador precisa revalidar a demanda.",
    keywords: ["volume", "demanda", "google ads", "pesquisa mensal", "revalidar", "targeting"],
  },
  {
    id: "processar-kgr",
    title: "KGR",
    summary: "KGR é calculado automaticamente a partir de Resultado e Volume atuais e válidos.",
    description: "O KGR é uma evidência de apoio, não uma aprovação automática. O score só é atual quando os dois inputs canônicos estão disponíveis; aplicabilidade e decisão humana aparecem separadamente.",
    sections: [
      { heading: "Não é uma ação", body: "Não existe botão próprio para calcular KGR: ele acompanha a atualização dos dados necessários." },
      { heading: "Zero real", body: "Volume ou Resultado medido como zero é um dado válido; ausência de medição continua sendo desconhecida." },
    ],
    keywords: ["kgr", "cálculo", "resultado / volume", "aplicabilidade", "score", "zero", "pendente"],
  },
  {
    id: "processar-cpc",
    title: "CPC",
    summary: "CPC é o custo médio por clique informado pelo Google Ads.",
    description: "CPC ajuda a observar valor comercial e mídia paga junto da demanda. Ele vem da mesma medição de Volume e não cria uma etapa, botão ou provider separado.",
    keywords: ["cpc", "custo por clique", "google ads", "mídia paga", "valor comercial", "r$"],
  },
  {
    id: "processar-kd",
    title: "KD",
    summary: "KD é a dificuldade orgânica numérica disponível na evidência SEO.",
    description: "KD complementa Resultado e KGR como sinal do DataForSEO. Ele não altera intenção, não cria decisão automática e não deve ser confundido com concorrência paga ou com o cálculo KGR.",
    keywords: ["kd", "keyword difficulty", "dificuldade orgânica", "dataforseo", "seo", "resultado"],
  },
  {
    id: "processar-intencao",
    title: "Intenção",
    summary: "Intenção é a leitura canônica atual, depois das etapas e das decisões humanas registradas.",
    description: "A intenção lógica é uma proposta determinística. A IA pode conferir ou sugerir, mas somente a revisão humana confirma ou edita o valor consolidado.",
    keywords: ["intenção", "intenção lógica", "intenção externa", "canônica", "confirmada", "humana"],
  },
  {
    id: "processar-nicho",
    title: "Nicho",
    summary: "Nicho identifica o contexto de mercado associado à keyword.",
    description: "O nicho mostrado na tabela vem do KeywordDNA canônico, não de um campo paralelo ou de uma intenção externa. A lógica propõe e a revisão humana pode confirmar, editar ou confirmar desconhecido.",
    keywords: ["nicho", "nicho de mercado", "keyworddna", "contexto", "confirmar desconhecido"],
  },
  {
    id: "processar-funil",
    title: "Entender TOFU, MOFU e BOFU",
    summary: "O Funil indica em qual etapa da jornada a busca provavelmente se encontra.",
    description: "O Funil indica em qual etapa da jornada a busca provavelmente se encontra. A classificação é uma leitura de apoio: a lógica propõe, a IA pode revisar e a decisão humana consolida o KeywordDNA. Intenção e Funil são relacionados, mas não são a mesma coisa.",
    sections: [
      { heading: "TOFU — Topo do funil", body: "Busca ampla de descoberta ou aprendizado. A pessoa ainda está entendendo o tema ou explorando possibilidades. Exemplo: unhas em acrilico." },
      { heading: "MOFU — Meio do funil", body: "A pessoa já conhece o tema e começa a considerar, avaliar ou comparar alternativas. Exemplo: gel ou acrilico qual é melhor." },
      { heading: "BOFU — Fundo do funil", body: "A busca demonstra proximidade de uma ação, como contratar, comprar, agendar, pedir orçamento ou encontrar um serviço. Exemplos: unhas de gel preço e manicure perto de mim." },
      { heading: "Indefinido", body: "O processamento terminou, mas a expressão não fornece evidência suficiente para localizar a busca no funil. Indefinido não significa Pendente." },
      { heading: "Intenção e Funil", body: "Intenção e Funil são eixos relacionados, mas diferentes: a Intenção descreve o objetivo da busca; o Funil indica sua etapa provável na jornada. Uma keyword pode ter Intenção ambígua e Funil TOFU quando o tema é amplo e reconhecível, mas o objetivo exato ainda não está claro." },
    ],
    keywords: ["funil", "TOFU", "topo do funil", "topo", "MOFU", "meio do funil", "meio", "BOFU", "fundo do funil", "fundo", "jornada", "indefinido", "não classificável", "pendente"],
  },
  {
    id: "processar-silo",
    title: "Silo/Categoria",
    summary: "Silo/Categoria organiza a keyword editorialmente e é um dos campos operacionais da linha.",
    description: "Escolha ou mova a keyword para uma lista existente quando a organização editorial estiver definida. A alteração de organização não reescreve a leitura lógica nem os fatos medidos.",
    keywords: ["silo", "categoria", "lista", "organização editorial", "mover"],
  },
  {
    id: "processar-status",
    title: "Status",
    summary: "Status registra a decisão editorial da keyword; não representa publicação.",
    description: "Use Status para indicar o estado de decisão do Minerador. Consulte Vínculo separadamente para saber se existe uma página publicada ou uma relação com o site.",
    keywords: ["status", "status final", "decisão editorial", "aprovado", "publicado", "vínculo"],
  },
  {
    id: "conferir-site",
    title: "Conferir site",
    summary: "Verifica se a keyword já possui relação com uma página da marca.",
    description: "A conferência procura ou confirma uma página existente para registrar o vínculo. Ela não publica, não altera a página e não substitui a decisão do Minerador.",
    howToUse: [
      "Selecione uma ou mais keywords.",
      "Acione Conferir site e aguarde o aviso.",
      "Leia o vínculo e a evidência na linha ou no Perfil.",
    ],
    keywords: ["conferir site", "site", "página", "vínculo", "url", "publicação"],
  },
  {
    id: "logica",
    title: "Lógica",
    summary: "Interpreta deterministicamente o significado da keyword.",
    description: "A leitura identifica intenção, entidade, modificadores, nicho, funil e outros sinais do KeywordDNA. É a melhor leitura inicial disponível, não uma verdade final sem revisão.",
    howToUse: [
      "Selecione as keywords que deseja qualificar.",
      "Acione Lógica.",
      "Confira a leitura no Perfil antes de consultar ou revisar outras evidências.",
    ],
    keywords: ["lógica", "processar lógica", "intenção", "entidade", "modificadores", "nicho", "funil"],
  },
  {
    id: "volume",
    title: "Volume",
    summary: "Atualiza a demanda e as métricas disponíveis no Google Ads.",
    description: "Consulta Volume, CPC, tendência e concorrência Ads para as keywords selecionadas. Uma medição anterior é preservada como histórico; a etapa fica validada depois da execução e do readback canônico.",
    howToUse: [
      "Selecione as keywords que deseja medir.",
      "Acione Volume e acompanhe o progresso do lote.",
      "Confira os valores e a data da medição na tabela ou no Perfil.",
    ],
    keywords: ["google ads", "volume", "cpc", "demanda", "tendência", "concorrência ads", "revalidar"],
  },
  {
    id: "resultados",
    title: "Resultados",
    summary: "Mede Resultado, KD e outras evidências orgânicas disponíveis.",
    description: "A consulta de Resultados preserva a medição técnica e seus estados. Resultado/allintitle e Keyword Overview podem ter disponibilidade diferente; ausência de KD não apaga um Resultado confirmado.",
    howToUse: [
      "Selecione as keywords que deseja consultar.",
      "Acione Resultados e aguarde o aviso de processamento.",
      "Confira Resultado, KD e a situação de cada medição no Perfil.",
    ],
    keywords: ["resultados", "resultado", "allintitle", "dataforseo", "kd", "overview", "concorrência orgânica"],
  },
  {
    id: "ia",
    title: "IA",
    summary: "Revisa a leitura lógica diante das evidências reunidas.",
    description: "A IA funciona como uma segunda leitura crítica: identifica inconsistências, propõe correções semânticas e acrescenta informações úteis. Ela não altera os números dos provedores nem aprova a keyword sozinha.",
    howToUse: [
      "Execute a leitura lógica e reúna as evidências disponíveis.",
      "Acione IA e acompanhe as fases do processamento.",
      "Abra Revisar para decidir o que fazer com as sugestões.",
    ],
    keywords: ["ia", "revisão ia", "inteligência artificial", "concordâncias", "divergências", "enriquecimentos"],
  },
  {
    id: "revisao-humana",
    title: "Revisar",
    summary: "Confirma as decisões humanas necessárias para consolidar o KeywordDNA.",
    description: "A revisão mostra fatos medidos, concordâncias, divergências e enriquecimentos. Concordâncias podem ser resolvidas automaticamente; o usuário atua onde existe decisão real e conclui quando o gate estiver completo.",
    howToUse: [
      "Execute IA e abra Revisar.",
      "Resolva divergências e escolha incluir ou ignorar enriquecimentos.",
      "Trate a aplicabilidade KGR e acione Concluir revisão.",
    ],
    keywords: ["revisar", "revisão humana", "concluir revisão", "divergência", "enriquecimento", "decisão humana"],
  },
  {
    id: "estados-processos",
    title: "Entender os estados dos processos",
    summary: "Executando, concluído, falhou e pendente descrevem o estado da etapa, não a qualidade da keyword.",
    description: "A barra, os avisos e a linha indicam o andamento do lote. Uma etapa pode ter dados anteriores preservados e ainda aguardar uma revalidação atual; leia a evidência e o estado juntos.",
    keywords: ["estado", "pendente", "executando", "concluído", "falhou", "progresso", "barra"],
  },
  {
    id: "processar-revalidacao",
    title: "Distinguir dado importado de etapa validada",
    summary: "Snapshots da Descoberta acompanham a keyword, mas não marcam a etapa do Processador como concluída.",
    description: "Volume, Resultado, CPC, KD e histórico importados são preservados como proveniência. O check da etapa só aparece depois da medição oficial do Processador para a keyword atual.",
    keywords: ["revalidação", "snapshot", "importado", "etapa validada", "discovery", "proveniência", "freshness"],
  },
  {
    id: "processar-zero-ausencia",
    title: "Diferenciar zero de ausência",
    summary: "Zero medido é um dado; traço ou sem medição significa que não há valor confirmado.",
    description: "Não interprete uma célula vazia como zero e não trate uma falha como uma nova medição. O histórico anterior permanece preservado quando uma consulta não confirma um valor atual.",
    keywords: ["zero", "ausência", "sem medição", "não informado", "falha", "histórico"],
  },
  {
    id: "processar-progresso",
    title: "Acompanhar o progresso de um lote",
    summary: "A barra inferior mostra a etapa, o percentual e a quantidade de keywords em processamento.",
    description: "Enquanto uma ação está rodando, os botões principais ficam bloqueados para evitar duplicidade. O aviso final resume sucesso, ausência de alteração ou falhas parciais.",
    keywords: ["progresso", "percentual", "keywords", "lote", "processando", "bloqueado", "aviso"],
  },
];

const PROFILE_TOPICS: readonly ContextHelpTopic[] = [
  {
    id: "perfil-keyword",
    title: "Ler o Perfil da Keyword",
    summary: "O Perfil organiza o KeywordDNA pela ordem em que os dados foram construídos.",
    description: "Use o Perfil para percorrer identidade, Leitura lógica, Google Ads, DataForSEO, Revisão Humana, Decisão e Proveniência. Cards vazios não representam etapas pendentes; a barra de processos mostra esse estado.",
    keywords: ["perfil da keyword", "keyworddna", "identidade", "leitura lógica", "decisão", "proveniência"],
  },
  {
    id: "perfil-leitura-logica",
    title: "Ler a Leitura lógica",
    summary: "Mostra a interpretação inicial e os detalhes que sustentam a proposta do KeywordDNA.",
    description: "Intenção, nicho, funil, entidade, modificadores, confiança e ambiguidade aparecem no resumo. Os detalhes profundos e evidências ficam recolhidos para consulta quando necessário.",
    keywords: ["leitura lógica", "intenção", "nicho", "funil", "entidade", "modificadores", "ambiguidade", "confiança"],
  },
  {
    id: "perfil-google-ads",
    title: "Ler as evidências do Google Ads",
    summary: "Reúne Volume, CPC, tendência, concorrência Ads e o contexto da medição.",
    description: "Esse card responde quanto a keyword é procurada e quais sinais comerciais foram retornados. O histórico e a origem da medição continuam disponíveis na proveniência.",
    keywords: ["perfil google ads", "volume", "cpc", "tendência", "concorrência ads", "demanda"],
  },
  {
    id: "perfil-dataforseo",
    title: "Ler as evidências do DataForSEO",
    summary: "Reúne Resultado, KD e as evidências SEO externas da keyword.",
    description: "Resultado representa a concorrência orgânica medida; KD, intenção externa e sinais de links complementam a análise quando retornados. A intenção externa é uma validação independente e não toma o lugar da intenção canônica.",
    keywords: ["perfil dataforseo", "resultado", "allintitle", "kd", "intenção externa", "backlinks", "referring domains"],
  },
  {
    id: "perfil-revisao-humana",
    title: "Ler a Revisão Humana no Perfil",
    summary: "Concentra fatos, resumo da IA, KGR, pendências e ações de consolidação.",
    description: "A revisão separa concordâncias resolvidas, divergências que exigem escolha e enriquecimentos que podem ser incluídos ou ignorados. KGR e sua aplicabilidade aparecem como evidência e decisão própria.",
    keywords: ["perfil revisão humana", "concordância", "divergência", "enriquecimento", "kgr", "concluir"],
  },
  {
    id: "perfil-decisao",
    title: "Usar o card Decisão",
    summary: "O card Decisão resume os sinais necessários para escolher o destino da keyword.",
    description: "Volume, CPC, Resultado, KGR, KD, Intenção, IA, DNA e aplicabilidade KGR aparecem como resumo. Históricos, justificativas e detalhes técnicos continuam nos cards de origem.",
    keywords: ["decisão", "resumo para decisão", "status final", "volume", "cpc", "resultado", "kgr", "kd", "dna"],
  },
  {
    id: "perfil-proveniencia",
    title: "Consultar a proveniência",
    summary: "Use a proveniência para auditar origem, data e histórico sem poluir a leitura operacional.",
    description: "A área técnica preserva medições anteriores, origem da Descoberta, datas, estados e detalhes das consultas. Ela serve para conferir rastreabilidade quando um valor ou etapa parecer diferente.",
    keywords: ["proveniência", "origem", "histórico", "medição", "data", "auditoria", "detalhes técnicos"],
  },
];

const REVIEW_DECISION_TOPICS: readonly ContextHelpTopic[] = [
  {
    id: "revisao-checklist",
    title: "Trabalhar com a revisão em checklist",
    summary: "A revisão humana pede ação somente onde a IA divergiu ou acrescentou algo novo.",
    description: "Concordâncias são resolvidas automaticamente. Divergências oferecem Manter lógica, Aceitar IA ou Editar; enriquecimentos oferecem Incluir ou Ignorar.",
    howToUse: [
      "Leia primeiro os fatos medidos e o resumo da IA.",
      "Resolva cada divergência real e trate os enriquecimentos relevantes.",
      "Conclua a revisão quando não houver pendência aberta.",
    ],
    keywords: ["checklist", "concordância", "divergência", "enriquecimento", "manter lógica", "aceitar ia", "editar"],
  },
  {
    id: "revisao-divergencias",
    title: "Resolver uma divergência da IA",
    summary: "Divergência é uma sugestão diferente da leitura lógica que precisa de decisão humana.",
    description: "Compare o valor lógico, a sugestão da IA e o motivo apresentado. A escolha humana pode manter a lógica, aceitar a sugestão ou editar o campo.",
    keywords: ["divergência", "manter lógica", "aceitar ia", "editar", "sugestão", "motivo"],
  },
  {
    id: "revisao-enriquecimentos",
    title: "Tratar enriquecimentos",
    summary: "Enriquecimento é uma sugestão nova da IA, não uma contradição do valor lógico.",
    description: "Leia a sugestão e inclua ou ignore conforme sua utilidade para o DNA. Incluir uma sugestão não significa aceitar toda a análise da IA.",
    keywords: ["enriquecimento", "incluir", "ignorar", "sugestão semântica", "ia"],
  },
  {
    id: "revisao-kgr",
    title: "Tratar a aplicabilidade do KGR",
    summary: "A pessoa decide se o KGR é aplicável ao caso; o score técnico permanece separado.",
    description: "Confira Volume, Resultado e o score calculado antes de escolher Aplicável, Não aplicável ou manter Pendente. Um score desfavorável não bloqueia sozinho uma decisão humana aprovada.",
    keywords: ["kgr", "aplicável", "não aplicável", "pendente", "score", "decisão humana"],
  },
  {
    id: "revisao-concluir",
    title: "Concluir ou reabrir uma revisão",
    summary: "Concluir confirma a consolidação; Reabrir permite revisar novamente sem refazer medições.",
    description: "A conclusão exige IA executada, KGR tratado quando aplicável, divergências resolvidas e nenhuma alteração aberta sem salvar. Reabrir cria uma cópia de trabalho e mantém os fatos medidos somente leitura.",
    keywords: ["concluir revisão", "reabrir", "revisar novamente", "cancelar", "cópia de trabalho", "pendências"],
  },
  {
    id: "decisao-final",
    title: "Escolher o Status final",
    summary: "Status final registra a decisão do usuário depois da leitura e da revisão.",
    description: "Use os sinais do card Decisão para escolher o estado editorial adequado. Status não executa provider, não publica a keyword e não transforma Vínculo em publicação.",
    keywords: ["status final", "decisão", "aprovado", "pendente", "bloqueado", "publicação", "vínculo"],
  },
];

export const MINERADOR_CONTEXT_HELP: ContextHelpAreaDefinition = {
  area: "minerador",
  title: "Minerador",
  topics: [
    ...GENERAL_TOPICS,
    ...DISCOVERY_TOPICS,
    ...PROCESSOR_TOPICS,
    ...PROFILE_TOPICS,
    ...REVIEW_DECISION_TOPICS,
  ],
};
