var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/marca/brand-dna/route.js")
R.c("server/chunks/[root-of-the-server]__0d5quxj._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_16q816f.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/lib_arquiteto_contracts_ts_0g3l3tz._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/[root-of-the-server]__163w3q6._.js")
R.c("server/chunks/lib_server_authz_ts_1eaen9x._.js")
R.c("server/chunks/_0pvv9t6._.js")
R.c("server/chunks/_next-internal_server_app_api_marca_brand-dna_route_actions_1bay-c9.js")
R.m(66579)
module.exports=R.m(66579).exports
