var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/editorial/views/route.js")
R.c("server/chunks/[root-of-the-server]__0p3xtmz._.js")
R.c("server/chunks/lib_radar_analysis-contracts_ts_1kx-j8l._.js")
R.c("server/chunks/lib_arquiteto_contracts_ts_0g3l3tz._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_1marlhx._.js")
R.c("server/chunks/_0pvv9t6._.js")
R.c("server/chunks/[root-of-the-server]__163w3q6._.js")
R.c("server/chunks/lib_server_authz_ts_1eaen9x._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/lib_server_editorial-repositories_ts_0mmc2vz._.js")
R.c("server/chunks/lib_0-wij20._.js")
R.c("server/chunks/_next-internal_server_app_api_editorial_views_route_actions_0b_4owi.js")
R.m(88692)
module.exports=R.m(88692).exports
