var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/arquiteto/serp/route.js")
R.c("server/chunks/lib_0-wij20._.js")
R.c("server/chunks/[root-of-the-server]__0e0dyo1._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/lib_server_authz_ts_1eaen9x._.js")
R.c("server/chunks/[root-of-the-server]__163w3q6._.js")
R.c("server/chunks/lib_arquiteto_contracts_ts_0g3l3tz._.js")
R.c("server/chunks/_0pvv9t6._.js")
R.c("server/chunks/_next-internal_server_app_api_arquiteto_serp_route_actions_1ht3cg0.js")
R.m(79149)
module.exports=R.m(79149).exports
