var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/inteligencia/route.js")
R.c("server/chunks/[root-of-the-server]__1vby2rk._.js")
R.c("server/chunks/lib_arquiteto_contracts_ts_0g3l3tz._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__163w3q6._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/lib_server_authz_ts_1eaen9x._.js")
R.c("server/chunks/_0pvv9t6._.js")
R.c("server/chunks/_next-internal_server_app_api_inteligencia_route_actions_09ccr2a.js")
R.m(70151)
module.exports=R.m(70151).exports
