"use client";

import { useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { Check, Users } from "lucide-react";
import { useBrand } from "@/components/brand-context";
import { approvedArticleVersions } from "@/lib/editorial/operational-flow";
import { adaptLegacyBrand } from "@/lib/editorial/adapters";
import { DataOriginBadge, EmptyPipelineState, HumanDecisionRequired, VersionBadge } from "@/components/editorial/pipeline-ui";
import { BrandDnaPanel } from "./brand-dna-panel";
import { SiteSitemapPanel } from "./site-sitemap-panel";
import { normalizeSiteUrl } from "@/lib/marca/site-domain";
import { ModuleHeader, Field, btn, field, card, Metric, LocalCollection, sessionId, useReadyPipeline } from "@/components/editorial/operational-screen-shared";

export function BrandPage({ initialSection = "visao" }: { initialSection?: string }) {
  const { activeBrand, refreshBrands, userRole, selectedBrandId } = useBrand(); const { data: session } = useSession(); const { pipeline, state } = useReadyPipeline();
  const [section, setSection] = useState(initialSection); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [inviteOpen, setInviteOpen] = useState(false); const [invite, setInvite] = useState({ email: "", role: "writer", expiresInDays: 7, modules: ["redator"], actions: ["view", "edit", "comment"] });
  const [form, setForm] = useState({ nome: activeBrand?.nome || "", site_url: activeBrand?.site_url || "", nicho: activeBrand?.nicho || "", localizacao: activeBrand?.localizacao || "", dna_diretrizes: activeBrand?.dna_diretrizes || "" });
  useEffect(() => { const timer = window.setTimeout(() => { if (activeBrand) setForm({ nome: activeBrand.nome || "", site_url: activeBrand.site_url || "", nicho: activeBrand.nicho || "", localizacao: activeBrand.localizacao || "", dna_diretrizes: activeBrand.dna_diretrizes || "" }); }, 0); return () => window.clearTimeout(timer); }, [activeBrand]);
  if (state || !pipeline.snapshot || !activeBrand) return state;
  const legacy = adaptLegacyBrand(pipeline.snapshot); const sections = [["visao", "Visão geral"], ["site", "Site e Sitemap"], ["dna", "DNA"], ["materiais", "Materiais"], ["skills", "Skills e prompts"], ["equipe", "Equipe"], ["configuracoes", "Configurações"]];
  const save = async (overrides: Partial<typeof form> = {}, rethrow = false) => { setSaving(true); setMessage(""); const nextForm = { ...form, ...overrides }; try { const response = await fetch("/api/marcas", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: activeBrand.id, ...nextForm, silos_existentes: activeBrand.silos_existentes }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Erro ao salvar."); await refreshBrands(); setForm(nextForm); setMessage("Marca atualizada."); } catch (error) { const message = error instanceof Error ? error.message : "Erro ao salvar."; setMessage(message); if (rethrow) throw new Error(message); } finally { setSaving(false); } };
  const sendInvite = async () => { setMessage(""); const expiresAt = new Date(Date.now() + invite.expiresInDays * 86400000).toISOString(); const input = { email: invite.email, role: invite.role, expiresAt, permissions: invite.modules.map(module => ({ module, actions: invite.actions })), createdBy: sessionId(session) };
    try { const response = await fetch("/api/editorial/invitations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ brandId: selectedBrandId, ...input }) }); const body = await response.json();
      if (!response.ok && body.code === "persistence_unavailable") { pipeline.createInvitation(input as Parameters<typeof pipeline.createInvitation>[0]); setInviteOpen(false); setMessage("Convite mantido apenas localmente; a migration de persistência ainda não foi aplicada e nenhum e-mail foi enviado."); return; }
      if (!response.ok) throw new Error(body.error || "Convite inválido."); pipeline.addInvitation(body.invitation); setInviteOpen(false); setMessage(body.message);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Erro ao criar convite."); } };
  return <><ModuleHeader title="Marca" description="Organização, BrandDNA, materiais, equipe e configurações."/><main className="p-3"><div className="mb-3 flex flex-wrap gap-1">{sections.map(([id, label]) => <button key={id} onClick={() => setSection(id)} className={`${btn} ${section === id ? "border-indigo-500 text-white" : ""}`}>{label}</button>)}</div>
    {message && <p className="mb-3 rounded border border-amber-900/40 bg-amber-950/20 p-2 text-[10px] text-amber-300">{message}</p>}
    {section === "visao" && <div className="grid gap-3 md:grid-cols-4"><Metric label="Keywords" value={pipeline.snapshot.keywords.length}/><Metric label="ArticleDNAs aprovados" value={approvedArticleVersions(pipeline.articleVersions, pipeline.versionEvents).length}/><Metric label="Radar" value={pipeline.radarItems.length}/><Metric label="Publicações" value={pipeline.operationalPublications.length + pipeline.snapshot.briefings.length}/><section className={`${card} md:col-span-4`}><h2 className="text-xs font-bold">Fluxo operacional</h2><p className="mt-2 text-[10px] text-slate-500">Minerador → Arquiteto → Radar → Planejador → Redator → Publicações</p></section></div>}
    {section === "site" && <SiteSitemapPanel brandId={activeBrand.id} siteUrl={activeBrand.site_url || ""} saving={saving} onSave={siteUrl => save({ site_url: normalizeSiteUrl(siteUrl) }, true)}/>}
    {section === "dna" && <div className="space-y-3"><BrandDnaPanel brandId={activeBrand.id} legacyGuidelines={activeBrand.dna_diretrizes || ""} niche={activeBrand.nicho || ""}/><div className="grid gap-3 lg:grid-cols-2"><section className={card}><div className="flex justify-between"><h2 className="text-xs font-bold">Cadastro real</h2><DataOriginBadge origin="real"/></div><dl className="mt-3 grid grid-cols-2 gap-3"><Field label="Nicho" value={activeBrand.nicho}/><Field label="Localização" value={activeBrand.localizacao}/><Field label="Silos" value={pipeline.snapshot.silos.length}/></dl></section><section className={card}><div className="flex justify-between"><h2 className="text-xs font-bold">Diretrizes legadas</h2><DataOriginBadge origin="legacy"/></div><div className="mt-2"><VersionBadge version="legacy" hash={legacy.contentHash}/></div><p className="mt-3 whitespace-pre-wrap text-[10px] text-slate-400">{legacy.rawGuidelines || "Não informado"}</p><p className="mt-2 text-[9px] text-amber-400">Não é BrandDNA estruturado ou aprovado.</p></section></div></div>}
    {section === "materiais" && <LocalCollection title="Materiais da marca" count={pipeline.materials.length} description="Contratos locais; persistência aguarda migration."/>}
    {section === "skills" && <div className="grid gap-3 md:grid-cols-2"><LocalCollection title="Skills" count={pipeline.skills.length} description="Regras reutilizáveis aprovadas pela marca."/><LocalCollection title="Prompts" count={pipeline.prompts.length} description="Prompts permanentes ou específicos de artigo."/></div>}
    {section === "equipe" && <div className="space-y-3"><section className={card}><div className="flex items-center justify-between"><div><h2 className="text-xs font-bold">Equipe e acessos</h2><p className="mt-1 text-[10px] text-slate-500">Permissões são granulares por módulo e ação.</p></div><button className={btn} onClick={() => setInviteOpen(value => !value)}><Users className="mr-1 h-3 w-3"/>Convidar colaborador</button></div>{inviteOpen && <div className="mt-3 grid gap-2 border-t border-slate-850 pt-3 md:grid-cols-4"><input className={field} type="email" placeholder="email@empresa.com" value={invite.email} onChange={event => setInvite(current => ({ ...current, email: event.target.value }))}/><select className={field} value={invite.role} onChange={event => setInvite(current => ({ ...current, role: event.target.value }))}>{["strategist", "analyst", "planner", "writer", "editor", "reviewer", "medical_reviewer", "publisher", "viewer", "external_collaborator"].map(role => <option key={role}>{role}</option>)}</select><select className={field} value={invite.modules[0]} onChange={event => setInvite(current => ({ ...current, modules: [event.target.value] }))}>{["marca", "minerador", "arquiteto", "radar", "planejador", "redator", "publicacoes"].map(module => <option key={module}>{module}</option>)}</select><button className={btn} onClick={() => void sendInvite()} disabled={!invite.email}>Criar convite pendente</button><label className="md:col-span-4 text-[9px] text-slate-500">Ações<div className="mt-1 flex flex-wrap gap-2">{["view", "comment", "edit", "write", "review", "approve", "export", "publish"].map(action => <label key={action} className="flex items-center gap-1"><input type="checkbox" checked={invite.actions.includes(action)} onChange={event => setInvite(current => ({ ...current, actions: event.target.checked ? [...current.actions, action] : current.actions.filter(item => item !== action) }))}/>{action}</label>)}</div></label></div>}</section>
      {pipeline.invitations.length ? <div className="overflow-x-auto rounded border border-slate-900"><table className="w-full text-[10px]"><thead className="bg-slate-950 text-slate-600"><tr><th className="p-2 text-left">E-mail</th><th>Papel</th><th>Escopo</th><th>Validade</th><th>Status</th><th>Ações</th></tr></thead><tbody>{pipeline.invitations.map(item => <tr key={item.id} className="border-t border-slate-900"><td className="p-2">{item.email}</td><td className="text-center">{item.role}</td><td className="text-center">{item.permissions.map(permission => `${permission.module}: ${permission.actions.join(", ")}`).join(" · ")}</td><td className="text-center">{new Date(item.expiresAt).toLocaleDateString("pt-BR")}</td><td className="text-center">{item.status} · e-mail não enviado</td><td className="space-x-1 p-2 text-right"><button className={btn} disabled={item.status !== "pending"} onClick={() => pipeline.updateInvitationStatus(item.id, "cancelled")}>Cancelar</button><button className={btn} onClick={() => pipeline.updateInvitationStatus(item.id, item.status === "suspended" ? "pending" : "suspended")}>{item.status === "suspended" ? "Reativar" : "Suspender"}</button><button className={btn} onClick={() => pipeline.updateInvitationStatus(item.id, "revoked")}>Revogar</button></td></tr>)}</tbody></table></div> : <EmptyPipelineState title="Nenhum convite" description="O adaptador de desenvolvimento não envia e-mail e mantém convites apenas nesta sessão."/>}<HumanDecisionRequired>Convites foram validados no servidor, mas ainda não persistem. O papel “cliente” continua como responsável legado da própria marca.</HumanDecisionRequired></div>}
    {section === "configuracoes" && <section className={`${card} max-w-4xl`}><div className="flex justify-between"><h2 className="text-xs font-bold">Configurações da empresa</h2><span className="text-[9px] text-slate-600">Acesso: {userRole}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{(["nome", "nicho", "localizacao"] as const).map(key => <label key={key} className="text-[9px] text-slate-500">{key}<input value={form[key]} onChange={event => setForm(current => ({ ...current, [key]: event.target.value }))} className={`${field} mt-1`}/></label>)}<p className="rounded border border-slate-900 bg-black/40 p-2 text-[10px] text-slate-500 md:col-span-2">O endereço do site agora é gerenciado na aba <strong className="text-slate-300">Site e Sitemap</strong>.</p><label className="md:col-span-2 text-[9px] text-slate-500">Diretrizes<textarea value={form.dna_diretrizes} onChange={event => setForm(current => ({ ...current, dna_diretrizes: event.target.value }))} rows={8} className="mt-1 w-full rounded border border-slate-800 bg-black p-2 text-xs text-slate-200"/></label></div><button disabled={saving} onClick={() => void save()} className={`${btn} mt-3`}><Check className="mr-1 h-3 w-3"/>{saving ? "Salvando…" : "Salvar configuração existente"}</button></section>}
  </main></>;
}

