// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(admin)/admin/marcas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marcas">> = Specific
  const handler = {} as typeof import("../../app/(admin)/admin/marcas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/arquiteto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/arquiteto">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/arquiteto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/conta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conta">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/conta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/inteligencia/[etapa]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inteligencia/[etapa]">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/inteligencia/[etapa]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/inteligencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inteligencia">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/inteligencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/marca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marca">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/marca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/minerador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/minerador">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/minerador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perfil">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/planejador/[contentPlanId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planejador/[contentPlanId]">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/planejador/[contentPlanId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/planejador/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planejador">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/planejador/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/publicacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/publicacoes">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/publicacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/radar/[articleId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/radar/[articleId]">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/radar/[articleId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/radar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/radar">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/radar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/redator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/redator">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/redator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze">> = Specific
  const handler = {} as typeof import("../../app/api/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/arquiteto/article-dna/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arquiteto/article-dna">> = Specific
  const handler = {} as typeof import("../../app/api/arquiteto/article-dna/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/arquiteto/publication/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arquiteto/publication/verify">> = Specific
  const handler = {} as typeof import("../../app/api/arquiteto/publication/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/arquiteto/serp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arquiteto/serp">> = Specific
  const handler = {} as typeof import("../../app/api/arquiteto/serp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/arquiteto/silo-dna/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arquiteto/silo-dna">> = Specific
  const handler = {} as typeof import("../../app/api/arquiteto/silo-dna/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/arquiteto/silo-page/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arquiteto/silo-page">> = Specific
  const handler = {} as typeof import("../../app/api/arquiteto/silo-page/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/google-client-id/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google-client-id">> = Specific
  const handler = {} as typeof import("../../app/api/auth/google-client-id/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clusterize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clusterize">> = Specific
  const handler = {} as typeof import("../../app/api/clusterize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial/documents">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial/invitations">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/radar-analysis/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial/radar-analysis/extract">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/radar-analysis/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/radar-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial/radar-analysis">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/radar-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/serp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial/serp">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/serp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial/views">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/workflow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial/workflow">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/workflow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial/workspace">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate-briefing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-briefing">> = Specific
  const handler = {} as typeof import("../../app/api/generate-briefing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inteligencia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inteligencia">> = Specific
  const handler = {} as typeof import("../../app/api/inteligencia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marca/brand-dna/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marca/brand-dna">> = Specific
  const handler = {} as typeof import("../../app/api/marca/brand-dna/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marca/site/import/keywords/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marca/site/import/keywords">> = Specific
  const handler = {} as typeof import("../../app/api/marca/site/import/keywords/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marca/site/lists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marca/site/lists">> = Specific
  const handler = {} as typeof import("../../app/api/marca/site/lists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marca/site/page/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marca/site/page/verify">> = Specific
  const handler = {} as typeof import("../../app/api/marca/site/page/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marca/site/sitemap/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marca/site/sitemap/sync">> = Specific
  const handler = {} as typeof import("../../app/api/marca/site/sitemap/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marca/site/sitemap/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marca/site/sitemap/test">> = Specific
  const handler = {} as typeof import("../../app/api/marca/site/sitemap/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/marcas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marcas">> = Specific
  const handler = {} as typeof import("../../app/api/marcas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mine/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mine">> = Specific
  const handler = {} as typeof import("../../app/api/mine/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/process-intent-niche/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/process-intent-niche">> = Specific
  const handler = {} as typeof import("../../app/api/process-intent-niche/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/publicacoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/publicacoes">> = Specific
  const handler = {} as typeof import("../../app/api/publicacoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/redator/guardian/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/redator/guardian">> = Specific
  const handler = {} as typeof import("../../app/api/redator/guardian/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/redator/improve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/redator/improve">> = Specific
  const handler = {} as typeof import("../../app/api/redator/improve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/redator/section/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/redator/section">> = Specific
  const handler = {} as typeof import("../../app/api/redator/section/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/revalidate-structure/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate-structure">> = Specific
  const handler = {} as typeof import("../../app/api/revalidate-structure/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/volume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/volume">> = Specific
  const handler = {} as typeof import("../../app/api/volume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(workspace)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(workspace)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
