var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/marcas/route.js")
R.c("server/chunks/[externals]__0sh8su4._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0fyt81q.js")
R.c("server/chunks/_0pvv9t6._.js")
R.c("server/chunks/lib_server_authz_ts_1eaen9x._.js")
R.c("server/chunks/[root-of-the-server]__163w3q6._.js")
R.c("server/chunks/_next-internal_server_app_api_marcas_route_actions_0536-_b.js")
R.m(11978)
module.exports=R.m(11978).exports
