"use client";

import Link from "next/link";
import { useState } from "react";
import { useEditorialPipeline } from "@/components/editorial-pipeline-context";
import { AlertTriangle } from "lucide-react";
import { ProfessionalWriter } from "@/components/editorial/professional-writer";
import { ProvenancePanel, EmptyPipelineState } from "@/components/editorial/pipeline-ui";
import type { ContentDocument } from "@/lib/arquiteto/contracts";
import { Field, card, btn, ModuleHeader, useOperationalRouter, useReadyPipeline } from "@/components/editorial/operational-screen-shared";

export function WriterPage({ initialArticleId = null, initialDocumentId = null }: { initialArticleId?: string | null; initialDocumentId?: string | null }) {
  return <ProfessionalWriter initialArticleId={initialArticleId} initialDocumentId={initialDocumentId}/>;
}

/** @deprecated Mantido temporariamente apenas para reversao visual da sprint anterior. */
export function LegacyWriterPrototype({ initialArticleId = null }: { initialArticleId?: string | null }) {
  const router = useOperationalRouter(); const { pipeline, state } = useReadyPipeline(); const [leftOpen, setLeftOpen] = useState(true); const [rightOpen, setRightOpen] = useState(true); const [fullscreen, setFullscreen] = useState(false);
  const requestedId = initialArticleId;
  if (state) return state; const documents = Object.values(pipeline.documents); const document = documents.find(item => item.articleDnaRef.entityId === requestedId) || documents[0];
  if (!document) return <><ModuleHeader title="Redator" description="Documento editorial e Guardião."/><main className="p-4"><EmptyPipelineState title="Nenhum documento" description="Aprove um plano editorial e use “Redigir artigo” no Planejador." action={<Link className={btn} href="/planejador">Abrir Planejador</Link>}/></main></>;
  const articleId = document.articleDnaRef.entityId; const publication = pipeline.operationalPublications.find(item => item.documentId === document.id); const wordCount = document.blocks.reduce((sum, block) => sum + ("text" in block ? block.text.split(/\s+/).filter(Boolean).length : 0), 0);
  return <div className={`${fullscreen ? "fixed inset-0 z-[100] bg-[#07080b]" : "min-h-screen"} flex flex-col`}><ModuleHeader title="Redator" description={`${document.title} · rascunho local`} actions={<><button className={btn} onClick={() => setLeftOpen(value => !value)}>Fundamentos</button><button className={btn} onClick={() => setRightOpen(value => !value)}>Guardião</button><button className={btn} onClick={() => setFullscreen(value => !value)}>{fullscreen ? "Sair da tela cheia" : "Tela cheia"}</button></>}/><div className="border-b border-amber-900/40 bg-amber-950/20 px-3 py-2 text-[10px] text-amber-200"><AlertTriangle className="mr-1 inline h-3 w-3"/><strong>Editor rico bloqueado:</strong> Tiptap não está instalado. Este documento e seus vínculos são reais no estado local, mas os controles de edição permanecem desabilitados para não simular um editor profissional.</div><div className="flex items-center gap-1 overflow-x-auto border-b border-slate-850 bg-[#0b0c10] p-2">{["Desfazer", "Refazer", "H1", "H2", "H3", "H4", "Parágrafo", "Negrito", "Itálico", "Sublinhado", "Tachado", "Lista", "Tabela", "Link", "Link interno", "Fonte", "CTA", "Produto", "Comparação", "Imagem", "Comentário"].map(action => <button key={action} disabled className={btn}>{action}</button>)}<span className="ml-auto whitespace-nowrap text-[9px] text-slate-600">{wordCount} palavras · não salvo remotamente</span></div><main className={`grid min-h-0 flex-1 ${leftOpen && rightOpen ? "xl:grid-cols-[260px_minmax(780px,900px)_300px]" : leftOpen ? "xl:grid-cols-[260px_minmax(780px,900px)]" : rightOpen ? "xl:grid-cols-[minmax(780px,900px)_300px]" : "xl:grid-cols-[minmax(780px,900px)]"} justify-center gap-3 overflow-auto bg-[#111218] p-3`}>
    {leftOpen && <aside className="h-fit rounded border border-slate-800 bg-[#090a0e] p-3"><h2 className="text-[10px] font-bold uppercase text-slate-500">Fundamentos</h2><dl className="mt-3 space-y-2"><Field label="Plano editorial" value={document.contentPlanRef.versionId}/><Field label="Definição do artigo" value={document.articleDnaRef.versionId}/><Field label="Arquitetura do silo" value={document.siloDnaRef.versionId}/><Field label="Perfis das keywords" value={document.keywordDnaRefs.length}/><Field label="Links planejados" value={pipeline.internalLinks.filter(link => link.sourceArticleId === articleId).length}/><Field label="Fontes externas" value={pipeline.externalSources.filter(source => source.articleId === articleId).length}/><Field label="Status" value="Rascunho local; Tiptap pendente"/></dl><h3 className="mt-4 text-[9px] font-bold uppercase text-slate-600">Outline</h3>{document.blocks.filter(block => block.type === "heading").map(block => <button key={block.id} className="mt-1 block text-left text-[10px] text-slate-400">{"level" in block ? `H${block.level}` : ""} {"text" in block ? block.text : ""}</button>)}</aside>}
    <article className="min-h-[calc(100vh-180px)] w-full rounded-sm bg-white px-12 py-10 text-slate-900 shadow-2xl" aria-label="Documento editorial estruturado">{document.blocks.map(block => <ContentBlockView key={block.id} block={block}/>)}</article>
    {rightOpen && <aside className="h-fit rounded border border-slate-800 bg-[#090a0e] p-3"><h2 className="text-[10px] font-bold uppercase text-slate-500">Guardião por seção</h2><div className="mt-3 space-y-2">{pipeline.guardianFindings.filter(finding => finding.documentId === document.id).map(finding => <button key={finding.id} className="w-full rounded border border-amber-900/50 p-2 text-left text-[10px]" onClick={() => globalThis.document.getElementById(finding.sectionId)?.scrollIntoView({ behavior: "smooth", block: "center" })}><strong className="text-amber-400">{finding.category} · {finding.severity}</strong><p>{finding.message}</p><p className="text-slate-500">{finding.suggestion}</p></button>)}{["Cobertura semântica", "Intenção e entidades", "Naturalidade e repetição", "Canibalização", "Links e âncoras", "Fontes e YMYL", "E-E-A-T", "Aderência ao plano"].map(item => <div key={item} className="rounded border border-slate-800 p-2 text-[10px] text-slate-500">{item}: aguardando análise</div>)}</div><div className="mt-3 border-t border-slate-850 pt-3"><Field label="Slug" value={publication?.slug}/><Field label="Canonical" value="Não informado"/><Field label="Indexação" value="Controlada apenas no destino futuro"/></div><button className={`${btn} mt-3`} onClick={() => router.push(`/publicacoes?articleId=${articleId}`)}>Abrir em Publicações</button></aside>}
  </main></div>;
}

function ContentBlockView({ block }: { block: ContentDocument["blocks"][number] }) {
  return <section id={block.id} className="group relative mb-5 border-l-2 border-transparent pl-2 hover:border-module-accent/40">{block.type === "heading" && (block.level === 1 ? <h1 className="text-3xl font-bold">{block.text}</h1> : block.level === 2 ? <h2 className="text-2xl font-bold">{block.text}</h2> : <h3 className="text-xl font-bold">{block.text}</h3>)}{block.type === "paragraph" && <p className="leading-7">{block.text}</p>}{block.type === "list" && (block.ordered ? <ol className="list-decimal pl-6">{block.items.map(item => <li key={item}>{item}</li>)}</ol> : <ul className="list-disc pl-6">{block.items.map(item => <li key={item}>{item}</li>)}</ul>)}{block.type === "table" && <table className="w-full border-collapse">{[block.headers, ...block.rows].map((row, index) => <tr key={index}>{row.map(cell => <td key={cell} className="border p-2">{cell}</td>)}</tr>)}</table>}{block.type === "quote" && <blockquote className="border-l-4 pl-3 italic">{block.text}</blockquote>}{block.type === "CTA" && <div className="rounded border border-action-accent/30 bg-action-accent/5 p-3"><strong>CTA</strong><p>{block.text}</p></div>}{block.type === "internal_link" && <p>Link interno: <u>{block.anchor}</u></p>}{block.type === "external_source" && <p>Fonte externa: {block.claim} · {block.url || "URL pendente"}</p>}{block.type === "image_brief" && <div className="rounded border border-dashed p-3">Imagem: {block.objective}</div>}{block.type === "note" && <aside className="rounded bg-amber-50 p-3">Nota: {block.text}</aside>}{block.type === "source" && <p className="text-sm">Fonte: {block.note}</p>}{block.type === "product_block" && <div className="rounded border p-3"><strong>{block.title}</strong><p>{block.summary}</p></div>}{block.type === "comparison" && <div className="rounded border p-3"><strong>{block.title}</strong></div>}<div className="mt-2 opacity-0 transition-opacity group-hover:opacity-100"><ProvenancePanel keywordRefs={block.provenance.keywordDnaRefs} evidenceRefs={block.provenance.evidenceRefs} sourceIds={block.provenance.sourceIds}/></div></section>;
}
